import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import UseSiteSettings from "@/Components/UseSiteSettings/UseSiteSettings";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";

// Fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Next Starter Template",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <QueryProvider>
          <AuthProvider>
            <AosProvider>
              <Toaster />
              {/* <UseSiteSettings /> */}
              {children}
            </AosProvider>
            <Toaster />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
